/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';
import {
  MatchResults,
} from '@stencil/router';


export namespace Components {

  interface AppHome {}
  interface AppHomeAttributes extends StencilHTMLAttributes {}

  interface AppProfile {
    'match': MatchResults;
  }
  interface AppProfileAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface KanbanBoard {}
  interface KanbanBoardAttributes extends StencilHTMLAttributes {}

  interface KbBucket {}
  interface KbBucketAttributes extends StencilHTMLAttributes {}

  interface KbTask {
    'isDraggedOver': boolean;
  }
  interface KbTaskAttributes extends StencilHTMLAttributes {
    'isDraggedOver'?: boolean;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AppHome': Components.AppHome;
    'AppProfile': Components.AppProfile;
    'AppRoot': Components.AppRoot;
    'KanbanBoard': Components.KanbanBoard;
    'KbBucket': Components.KbBucket;
    'KbTask': Components.KbTask;
  }

  interface StencilIntrinsicElements {
    'app-home': Components.AppHomeAttributes;
    'app-profile': Components.AppProfileAttributes;
    'app-root': Components.AppRootAttributes;
    'kanban-board': Components.KanbanBoardAttributes;
    'kb-bucket': Components.KbBucketAttributes;
    'kb-task': Components.KbTaskAttributes;
  }


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLKanbanBoardElement extends Components.KanbanBoard, HTMLStencilElement {}
  var HTMLKanbanBoardElement: {
    prototype: HTMLKanbanBoardElement;
    new (): HTMLKanbanBoardElement;
  };

  interface HTMLKbBucketElement extends Components.KbBucket, HTMLStencilElement {}
  var HTMLKbBucketElement: {
    prototype: HTMLKbBucketElement;
    new (): HTMLKbBucketElement;
  };

  interface HTMLKbTaskElement extends Components.KbTask, HTMLStencilElement {}
  var HTMLKbTaskElement: {
    prototype: HTMLKbTaskElement;
    new (): HTMLKbTaskElement;
  };

  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement
    'app-profile': HTMLAppProfileElement
    'app-root': HTMLAppRootElement
    'kanban-board': HTMLKanbanBoardElement
    'kb-bucket': HTMLKbBucketElement
    'kb-task': HTMLKbTaskElement
  }

  interface ElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
    'kanban-board': HTMLKanbanBoardElement;
    'kb-bucket': HTMLKbBucketElement;
    'kb-task': HTMLKbTaskElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
